### ISSUE TITLE
Pause/Resume for upscaling process.

### ISSUE THREAD

**Issue by kodxana** [FoxtrotCore/FoxTrotUpscaler#2]
Is it possible to add pause/resume option for upscaling process cause I do not like running PC at night :)

**Comment by dmitri-mcguckin** [comment]
There already is a pause feature.

I won't lie, it's been probably a year or so since I've last looked at the interface but there is a button generally on the right side of the application that lets you pause the current process. Then, if you close the program and reopen it later with the cached frames still on disk, FTU will try to perform auto recovery to figure out where you last left off and start from there.

**Comment by kodxana** [comment]
I have tried doing that but it started going back to step one extracting frames.

**Comment by dmitri-mcguckin** [comment]
Yeah so that's actually intentional.

The application has the behavior of assuming that if you stop it in the middle of stage 1 (ffmpeg frame extraction) then the frames might not be good so it restarts that. If you let the program make it to stage 2 (waifu2x-caffe upscaling) the pausing will look at the temp frames folder and try to recover based on what's in there.


If it's still doing that even on stage 2 then more details about your setup and your issue would be nice.

**Comment by dmitri-mcguckin** [comment]
Haven't heard back from you in a while so I'm going to assume the problems or misunderstandings were cleared up.
