### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by kodxana** [FoxtrotCore/FoxTrotUpscaler#3]
Would it be possible to run tool on Linux it would be more performance improvment cause Linux have better VRAM managment over Windows :)

**Comment by dmitri-mcguckin** [comment]
We did manage to *"unofficially"* support it on linux with some effort required but because of the internal infrastructure and dependencies, (namely waifu2x-caffe and an older version of rawtherapee), we can't make it work seamlessly on linux without also changing the dependencies.

Some good news, though, we have on our backlog of things to do: FTUv2 and yes we plan to make it platform agnostic. Likely the interface will be web-based or something so we can get away from platform-specific libraries, or worse, frameworks that are in the middle of licensing pissing matches. *(cough, cough, ncurses/curses.h)*.

We'll be sure to announce this on our twitter [@foxtrotfanatics](https://twitter.com/foxtrotfanatics) when we start that project.

If you're looking for a video upscaler, there is [anime4k-git](https://aur.archlinux.org/packages/anime4k-git) in the Arch User Repository that might serve your needs in a more timely fashion.

We don't plan to update FTU anymore save for occasional security updates if/when needed.

Thanks for your interest.
